databases:
  - name: dp-canteen-db
    databaseName: dp_canteen
    user: dp_canteen_user
    plan: free

services:
  - type: web
    name: dp-canteen-api
    runtime: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn dp_canteen.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dp-canteen-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.11.4"
      - key: AES_SECRET_KEY
        sync: false  # Set this manually in Render dashboard
